export { default as Home } from './Home'
export { default as Blog } from './Blog'
export { default as About } from './About'
export { default as Posts } from './Posts'
export { default as ErrorPage } from './Errorpage'