export { default as Home } from "./Home/Home";
export { default as About } from "./About/About";
export { default as Posts } from "./Posts/Posts";
export { default as Post } from "./Post/Post";
export { default as Users } from "./Users/Users";
export { default as User } from "./User/User";
export { default as Photos } from "./Photos/Photos";
export { default as Comments } from "./Comments/Comments";
export { default as Error } from "./Error/Error";
